apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-searchnews
  namespace: nodejs-app-searchnews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app-searchnews
  template:
    metadata:
      labels:
        app: nodejs-app-searchnews
    spec:
      containers:
      - name: nodejs-app-searchnews
        image: rafaelgoncalvesmatos/nodejs-app-searchnews
        ports:
        - containerPort: 8000