apiVersion: v1
kind: Service
metadata:
  name: climate-change-api
  namespace: default
  labels:
    app: climate-change-api
spec:
  type: NodePort
  selector:
    app: climate-change-api
  ports:
    - name: climate-change-api
      port: 8000
      targetPort: 8000
      nodePort: 31100