apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-searchnews
  namespace: nodejs-app-searchnews
  labels:
    app: nodejs-app-searchnews
spec:
  type: NodePort
  selector:
    app: nodejs-app-searchnews
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30000